<?php

/**
 * @file
 * Install, update and uninstall functions for the LocalGov Live Preview module.
 */

/**
 * Implements hook_install().
 */
function localgov_live_preview_install() {
  \Drupal::messenger()->addStatus('Localgov Live Preview module installed.');
}

/**
 * Implements hook_uninstall().
 */
function localgov_live_preview_uninstall() {
  \Drupal::messenger()->addStatus('Localgov Live Preview module uninstalled.');
}
