<?php

/**
 * @file
 * Contains hooks and functionality for LocalGov Live Preview Microsites module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\EventSubscriber\MainContentViewSubscriber;
use Drupal\localgov_microsites_group\RolesHelper;

/**
 * @file
 * Primary module hooks for LocalGov Live Preview module.
 */

/**
 * Implements hook_localgov_microsites_roles_default().
 */
function localgov_live_preview_microsites_localgov_microsites_roles_default(): void {

  return [
    'global' => [
      RolesHelper::MICROSITES_CONTROLLER_ROLE => ['use localgov live preview'],
      RolesHelper::MICROSITES_EDITOR_ROLE => ['use localgov live preview'],
    ],
  ];

}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_live_preview_microsites_preprocess_page(&$variables): void {
  // Check if we are on a node page and are logged in.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node && \Drupal::currentUser()->isAuthenticated()) {
    // Add the live preview library.
    $variables['#attached']['library'][] = 'localgov_live_preview_microsites/localgov-live-preview-microsites';
  }
}

/**
 * Implements hook_entity_form_mode_alter().
 */
function localgov_live_preview_microsites_entity_form_mode_alter(&$form_mode, EntityInterface $entity): void {
  // Change the form mode for users with Administrator role.
  if ($entity->getEntityTypeId() == 'group') {
    // Check if the current request is for an Ajax modal/dialog.
    $wrapper_format = \Drupal::request()->query->get(MainContentViewSubscriber::WRAPPER_FORMAT);
    if (in_array($wrapper_format, ['drupal_dialog.off_canvas'], true)) {
      // We are inside a modal.
      $form_mode = 'localgov_live_preview';
    }
  }
}
